### ISSUE TITLE
Errors while setting up development

### ISSUE THREAD

**Issue by claaslisowski** [Y0nnyy/passman-ios#6] opened 2018-02-21 12:21 UTC
Thanks for this project.
I haven't done anything yet in react-native but I though I'll look into it, so far I've only done some test apps in Swift.

Setting up the development environment didn't seem to be difficult. I had to run install one dependency additionally as npm told me to do:
`npm install asyncstorage-down@3.0.0` 

When running `react-native run-ios` it says "BUILD SUCCEEDED" but then the Simulator starts and displays an error. See screenshot.
![screen shot 2018-02-21 at 13 11 31](https://user-images.githubusercontent.com/33903475/36479720-f552149e-1709-11e8-949b-31a6dbce5e21.png)

I've googled that and followed some [instructions](https://stackoverflow.com/questions/33538403/error-couldnt-find-preset-react-when-installed-using-npm-install-global-ba#33870638) but I don't know exactly which paths should be the `--watch` directory and the `--out-dir` (if required at all).

Is it possible that you give some more instructions, or can I upload some more log files to get this solved?

Thanks!

**Comment by Y0nnyy** [comment] 2018-02-21 21:41
Hey @claaslisowski! Thank you for checking out the project and testing it. 
I made some commits where i added the asyncstorage-down dependency, that should fix the ummet-peer-dependency error.
I also changed the `npm run-ios` execution step to `react-native run-ios` in the README.md. Thank you for pointing it out.

The error was in the `.babelrc`. This file says which preset should be used for compiling. Apparently the wrong preset was used. I changed it to the right one. 
After that the error was gone, but another error showed up and said `Crypto.js`is not found. This problem occurs if you want to use a non-react-native node library. So with the tool `rn-nodeify`the problem is gone (see Troubleshooting in the README.md). What it does exactly you can look up [here](https://www.npmjs.com/package/rn-nodeify). 
In the future we should use another approach to handle this.

So after `pulling` and executing `rn-nodeify --install`, `react-native run-ios`should work :)

**Comment by blacs30** [comment] 2018-02-22 00:36
Thank you @Y0nnyy for your prompt reply. It works now. I had to use some additional [steps](https://github.com/tradle/rn-nodeify) to install/use rn-nodeify.

I was able to login to Passman on my nextcloud 12 instance.

Nice work so far! 

You can close this issue, if you want.

**Closed** 2018-02-27 11:17 UTC
Labels: bug
